;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	LaTeX-insert-left-brace
	TeX-insert-backslash
	indent-for-tab-command
	undo-tree-visualize
	))

(setq mc/cmds-to-run-once
      '(
	c-electric-brace
	compile
	enlarge-window-horizontally
	))
